baseURL: "https://ohdair.github.io/" 
title: Knowing its time will come, the cosmos never envies the forsythia
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://raidho.tistory.com
          weight: 6

params:
    description: "I am a Professor of Philology at the Institute of Romance Philology in Regensburg, Germany. My research focuses mostly on Portuguese irregular verbs."
    author: Jaewpark
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Knowing its time will come, the cosmos never envies the forsythia
          subtitle: "코스모스는 개화할 것을 알기에 결코 개나리를 부러워하지 않습니다. 조금 늦어진 것처럼 느껴질지라도, 제 속도로 꾸준히 성장하고 있습니다. 이 여정은 다른 이들과의 비교가 아닌, 저와의 약속을 지키는 과정입니다. 봄이 오면 개나리가 피어나듯, 저 자신이 개화하는 날은 분명히 온다고 생각합니다."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Courses
              url: courses/
            - name: Data
              url: data/
            - name: Books
              url: books/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://raidho.tistory.com

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:ohdiar@gmail.com
        - name: GitHub
          url: https://github.com/ohdair

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "The cosmos never envies the forsythia"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2